# Internal helper functions shared by run_mr() and run_coloc()
# All functions in this file are @keywords internal and NOT exported.

#' Harmonise exposure and outcome data, filter, and deduplicate
#'
#' Wraps [TwoSampleMR::harmonise_data()], filters to `mr_keep == TRUE`,
#' and removes duplicate SNPs (keeping the first occurrence).
#'
#' @param exposure Data frame of formatted exposure data.
#' @param outcome Data frame of formatted outcome data.
#'
#' @return A data frame of harmonised data, filtered and deduplicated.
#'
#' @importFrom rlang .data
#' @keywords internal
harmonise_and_filter <- function(exposure, outcome) {
  harmonised <- TwoSampleMR::harmonise_data(
    exposure_dat = exposure,
    outcome_dat = outcome
  )

  # Guard: return 0-row frame if harmonisation produced no usable output
  # (e.g. no SNP overlap, or all SNPs removed as palindromic). This lets
  # run_mr() hit its nrow == 0 early-return rather than erroring on a missing
  # `mr_keep` column.
  if (nrow(harmonised) == 0 || !"mr_keep" %in% names(harmonised)) {
    return(harmonised[0, , drop = FALSE])
  }

  harmonised <- harmonised |>
    dplyr::filter(.data$mr_keep == TRUE) |>
    dplyr::filter(!duplicated(.data$SNP))

  harmonised
}

#' Compute LD correlation matrix from a local reference panel
#'
#' Calls [ieugwasr::ld_matrix()] and strips allele suffixes
#' (e.g. `rs123_A_G` -> `rs123`) from row and column names.
#'
#' @param snps Character vector of rsIDs.
#' @param bfile Path to PLINK bfile prefix (without .bed/.bim/.fam).
#' @param plink_bin Path to PLINK binary. If `NULL`, auto-detected via
#'   [genetics.binaRies::get_plink_binary()].
#'
#' @return A square correlation matrix with rsID-only row/column names.
#'
#' @keywords internal
compute_ld_matrix <- function(snps, bfile, plink_bin = NULL) {
  if (is.null(plink_bin)) {
    plink_bin <- genetics.binaRies::get_plink_binary()
  }

  ld <- ieugwasr::ld_matrix(
    variants = snps,
    bfile = bfile,
    plink_bin = plink_bin
  )

  # Strip allele suffixes: rs123_A_G -> rs123
  rownames(ld) <- stringr::str_remove(rownames(ld), "_.*")
  colnames(ld) <- stringr::str_remove(colnames(ld), "_.*")

  ld
}

#' Clump instruments using LD reference
#'
#' Computes pseudo p-values (to ensure correct ranking by PLINK) and
#' performs LD clumping via [ieugwasr::ld_clump()].
#'
#' Pseudo p-values are generated by:
#' 1. Computing z-scores: `beta / se`
#' 2. Computing precise -log10(p) via [Rmpfr::pnorm()]
#' 3. Ranking SNPs by -log10(p) descending
#' 4. Assigning evenly spaced pseudo p-values from 1e-100 to 0.9
#'
#' @param dat Data frame with columns `rsid`, `pval`, `id`, and optionally
#'   `beta` and `se` (used for pseudo p-value computation). If `beta` and
#'   `se` are absent, `pval` is used directly.
#' @param rsq_thresh R-squared clumping threshold.
#' @param clump_kb Clumping window in kb. Default 10000.
#' @param bfile Path to PLINK bfile prefix. If `NULL`, uses API clumping.
#' @param plink_bin Path to PLINK binary. If `NULL`, auto-detected.
#' @param pop Population for API clumping. Default `"EUR"`.
#'
#' @return Data frame of clumped variants (output of `ieugwasr::ld_clump()`).
#'
#' @keywords internal
clump_instruments <- function(
  dat,
  rsq_thresh,
  clump_kb = 10000,
  bfile = NULL,
  plink_bin = NULL,
  pop = "EUR"
) {
  # Compute pseudo p-values if beta and se are available
  if (all(c("beta", "se") %in% colnames(dat))) {
    dat <- dat |>
      dplyr::mutate(
        z = .data$beta / .data$se,
        log10p = sapply(
          -log10(
            2 *
              Rmpfr::pnorm(
                Rmpfr::mpfr(abs(.data$z), precBits = 100),
                lower.tail = FALSE
              )
          ),
          as.numeric
        )
      ) |>
      dplyr::arrange(dplyr::desc(.data$log10p)) |>
      dplyr::mutate(
        pval = seq(from = 1e-100, to = 0.9, length.out = dplyr::n())
      )
  }

  clump_args <- list(
    dat = dat[, c("rsid", "pval", "id")],
    clump_kb = clump_kb,
    clump_r2 = rsq_thresh
  )

  if (!is.null(bfile)) {
    if (is.null(plink_bin)) {
      plink_bin <- genetics.binaRies::get_plink_binary()
    }
    clump_args$bfile <- bfile
    clump_args$plink_bin <- plink_bin
  } else {
    if (!isTRUE(getOption("mrpipeline.api_message_shown"))) {
      cli::cli_inform(
        c(
          "i" = "Using API for LD clumping (population: {pop}).",
          "i" = "For large datasets, a local {.arg bfile} is recommended."
        )
      )
      options(mrpipeline.api_message_shown = TRUE)
    }
    clump_args$pop <- pop
  }

  do.call(ieugwasr::ld_clump, clump_args)
}

#' Align harmonised data to an LD matrix
#'
#' Subsets both the harmonised data frame and LD matrix to their
#' shared SNPs, and reorders both to match.
#'
#' @param harmonised_data Data frame with a `SNP` column.
#' @param ld_matrix Square matrix with rsID row/column names.
#'
#' @return A named list with elements:
#'   - `data`: subset and reordered data frame
#'   - `ld_matrix`: subset and reordered matrix
#'
#' @keywords internal
align_to_ld_matrix <- function(harmonised_data, ld_matrix) {
  shared <- intersect(harmonised_data$SNP, rownames(ld_matrix))

  if (length(shared) == 0) {
    cli::cli_abort("No SNPs in common between harmonised data and LD matrix.")
  }

  data_out <- harmonised_data[match(shared, harmonised_data$SNP), ]
  ld_out <- ld_matrix[shared, shared]

  list(data = data_out, ld_matrix = ld_out)
}

#' Convert effect allele frequency to minor allele frequency
#'
#' @param eaf Numeric vector of effect allele frequencies.
#'
#' @return Numeric vector of minor allele frequencies.
#'
#' @keywords internal
eaf_to_maf <- function(eaf) {
  ifelse(eaf < 0.5, eaf, 1 - eaf)
}

#' Resolve sample size from multiple sources
#'
#' Attempts to determine sample size from (in order of priority):
#' 1. An explicitly provided value
#' 2. The median of a data column
#' 3. `NULL` (caller decides whether to error or warn)
#'
#' @param explicit_n Explicit sample size (numeric scalar or `NULL`).
#' @param data_column Numeric vector (e.g. `samplesize.exposure` column),
#'   or `NULL`.
#' @param label Character label for messages (e.g. `"exposure"`).
#'
#' @return Integer sample size, or `NULL` if unavailable.
#'
#' @keywords internal
resolve_sample_size <- function(
  explicit_n = NULL,
  data_column = NULL,
  label = "dataset"
) {
  if (!is.null(explicit_n)) {
    return(as.integer(explicit_n))
  }

  if (!is.null(data_column) && length(data_column) > 0) {
    n <- stats::median(data_column, na.rm = TRUE)
    if (!is.na(n)) {
      cli::cli_inform(
        "Using median sample size from {label} data: {.val {as.integer(n)}}."
      )
      return(as.integer(n))
    }
  }

  NULL
}
